### ISSUE TITLE
No test data

### ISSUE THREAD

**Issue by sandyplus** [danlwarren/ENMTools#108]
Dear Dan,
Would you mind tell me where can I find the test data?
 
Best regards,
sandy.

```
> library("ENMTools")
> env.files <- list.files(path = "test/testdata/", pattern = "pc", full.names = TRUE)
> env <- stack(env.files)
Error in x[[1]] : subscript out of bounds
> names(env) <- c("layer.1", "layer.2", "layer.3", "layer.4")
Error in names(env) <- c("layer.1", "layer.2", "layer.3", "layer.4") : 
  object 'env' not found
```

**Comment by sandyplus** [comment]
I finally found them on the env-list branch. 
Thank you.

**Comment by danlwarren** [comment]
There's actually new test data built into the package (iberolacerta.clade and euro.worldclim), but the vignette has not yet been updated to reflect this.
