### ISSUE TITLE
error for install on windows 10

### ISSUE THREAD

**Issue by sandyplus** [danlwarren/ENMTools#111]
Dear Dan,
I tried to install ENMTools on windows 10, but got this error:
`Error : object 'descendants' is not exported by 'namespace:phyloclim'`
I also tried reinstalled phyloclim, but still got this error.
How can I install ENMTools on windows? Would you mind give me some suggestions?
Best regards,
sandy

PS:
```
install_github("danlwarren/ENMTools")
Downloading GitHub repo danlwarren/ENMTools@master
from URL https://api.github.com/repos/danlwarren/ENMTools/zipball/master
Installing ENMTools
"D:/Program Files/R-3.5.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/BNF-02/AppData/Local/Temp/RtmpaSDa7k/devtools354c3b254ca2/danlwarren-ENMTools-c1205e0"  \
  --library="D:/Program Files/R-3.5.0/library" --install-tests 

* installing *source* package 'ENMTools' ...
** R
** data
*** moving datasets to lazyload DB
** tests
** byte-compile and prepare package for lazy loading
Error : object 'descendants' is not exported by 'namespace:phyloclim'
ERROR: lazy loading failed for package 'ENMTools'
* removing 'D:/Program Files/R-3.5.0/library/ENMTools'
In R CMD INSTALL
Installation failed: Command failed (1)
```

**Comment by danlwarren** [comment]
Well the good news is that it isn't on your end.  It seems as though phyloclim was updated recently, and the new version doesn't export the descendants function.  I'll do something about that immediately.

**Comment by danlwarren** [comment]
Okay, I've got something up on the develop branch that may fix it.  Feel free to give it a shot if you have a chance; it's going through checks on Travis CI right now.

**Comment by sandyplus** [comment]
Dear Dan,
I finally figured out how to install the "develop" branch.
However, I still can not install this due to rJava error.
I searched all over the world, but still cannot find the solution.
Would you mind give me some suggestions?
Best regards,
Sandy
PS:
```
** testing if installed package can be loaded
*** arch - i386
Error: package or namespace load failed for 'ENMTools':
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error:  unable to load shared object ‘D:/Program Files/R-3.5.0/library/rJava/libs/i386/rJava.dll’：:
  LoadLibrary failure: %1 is not a valid Win32 application. in R
```

**Comment by danlwarren** [comment]
Did you see this blog post?

http://enmtools.blogspot.com/2018/05/issues-with-installing-enmtools-under.html

The error message is slightly different, but it might still help.

**Comment by sandyplus** [comment]
Thanks Dan.
Finally, I fixed the error.
I removed all PATH related to "java", then **Add jvm.dll to PATH** (adding "%JAVA_HOME%\jre\bin\server;" to PATH).
After that, I set up the JAVA_HOME in R:
`Sys.setenv(JAVA_HOME="C:\\Program Files\\Java\\jdk1.8.0_171\\")`.
Works for me.

**Comment by danlwarren** [comment]
Good to hear!  I'll add your fix to the discussion on the blog.
