### ISSUE TITLE
Error in env.overlap and identity.test

### ISSUE THREAD

**Issue by momeni133** [danlwarren/ENMTools#134]
Hello Dan, 
I ran "enmtools.maxent" for two species using a single repeat run to prevent the previous error. The run finished successfully without any error:
`library(dismo)
library(rJava)
library(rgdal)
library(sp)
library(parallel)
library(ENMTools)

env <- list.files(path= "C:/Users/iman/Desktop/maxent.r/ascii", pattern='asc', full.names=TRUE)
env_stck <- stack(env)
projection(env_stck) <- CRS("+init=EPSG:2059")

cheetah.range = raster("C:/Users/iman/Desktop/maxent.r/range/final/cheetah_r")

cheetah.occ <- read.table("C:/Users/iman/Desktop/maxent.r/cheetah.csv", header=TRUE, sep=',')[,-1]
cheetah_backg <- read.table("C:/Users/iman/Desktop/maxent.r/background_carn.csv", header=TRUE, sep=',')

cheetah <- enmtools.species()
cheetah$species.name <- "cheetah"
cheetah$presence.points <- cheetah.occ
cheetah$background.points <- cheetah_backg
cheetah$range <- cheetah.range
my.args = c(
  "outputformat=cloglog",
  "jackknife=TRUE",
  "pictures=true",
  "betamultiplier=8",
  "replicatetype=crossvalidate",
  "linear=TRUE",
  "quadratic=TRUE",
  "product=TRUE",
  "threshold=FALSE",
  "hinge=TRUE",
  "outputfiletype=asc",
  "outputgrids=TRUE",
  "threads=7",
  "askoverwrite=false",
  "writeplotdata=TRUE",
  "maximumiterations=5000")

outdir = "C:/Users/iman/Desktop/maxent.r/output/cheetah"

cheetah.mx <- enmtools.maxent(cheetah, env_stck, factors='lulc', args= my.args, path=outdir)

leopard.range = raster("C:/Users/iman/Desktop/maxent.r/range/final/leopard_r")

leopard.occ <- read.table("C:/Users/iman/Desktop/maxent.r/leopard.csv", header=TRUE, sep=',')[,-1]
leopard_backg <- read.table("C:/Users/iman/Desktop/maxent.r/background_carn.csv", header=TRUE, sep=',')

leopard <- enmtools.species()
leopard$species.name <- "leopard"
leopard$presence.points <- leopard.occ
leopard$background.points <- leopard_backg
leopard$range <- leopard.range
my.args = c(
  "outputformat=cloglog",
  "jackknife=TRUE",
  "pictures=true",
  "betamultiplier=5.5",
  "replicatetype=crossvalidate",
  "linear=TRUE",
  "quadratic=TRUE",
  "product=FALSE",
  "threshold=FALSE",
  "hinge=TRUE",
  "outputfiletype=asc",
  "outputgrids=TRUE",
  "threads=7",
  "askoverwrite=false",
  "writeplotdata=TRUE",
  "maximumiterations=5000")

outdir = "C:/Users/iman/Desktop/maxent.r/output/leopard"

leopard.mx <- enmtools.maxent(leopard, env_stck, factors='lulc', args= my.args, path=outdir)
`

 But unfortunately when I try to calculate env.overlap using the code `overlap = env.overlap(cheetah.mx, leopard.mx, env_stck, tolerance = 0.001, max.reps = 10, cor.method = "spearman", chunk.size = 1e+05)
` I receive the error "Error in if (sd(pred1) == 0 | sd(pred2) == 0) { : 
  missing value where TRUE/FALSE needed"
![error_overlap](https://user-images.githubusercontent.com/33343341/44627615-19c5d300-a946-11e8-8ee9-16f7c1a35890.jpg)

Also when I try to run identity test using the code `identity.test(cheetah,leopard,env_stck, type="rf", nreps = 99, nback = 1000, bg.source = "points")` I receive the error "Error in if (sd(pred1) == 0 | sd(pred2) == 0) { : 
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In randomForest.default(m, y, ...) :
  The response has five or fewer unique values.  Are you sure you want to do regression?
2: In randomForest.default(m, y, ...) :
  The response has five or fewer unique values.  Are you sure you want to do regression?
3: In sqrt(getValues(x)) : NaNs produced
4: In sqrt(getValues(x)) : NaNs produced"

![error_identity](https://user-images.githubusercontent.com/33343341/44627817-78408080-a949-11e8-9532-87bd3629c07c.jpg)

I tried and checked everything several times, but I haven't found any error in my codes.
Do you have any idea to solve the problem?

**Comment by danlwarren** [comment]
Sorry for the slow reply.  It's quite difficult to figure out what's going on with this over the internet.  Do you have a Dropbox folder or something you could share?

**Comment by momeni133** [comment]
Hello Dan,
Thanks for your response. 
I sent the data and script to your Email.

**Comment by danlwarren** [comment]
For my own future reference: it looks like this issue was due to not having mins and maxes set on the raster stack.  This is fixable by doing "env_stck <- setMinMax(env_stck)" before running analyses..
