### ISSUE TITLE
Predict function not found

### ISSUE THREAD

**Issue by hmorzaria** [danlwarren/ENMTools#137]
I want to use the predict function, but it does not seem to be properly defined in the package. I see it defined in enmtools.maxent.R (function predict.enmtools.maxent),  however:

> predict.enmtools.maxent
Error: object 'predict.enmtools.maxent' not found
 
It also does not appear in the package documentation, am I missing something?

I tried updating ENMTools as well.

**Comment by danlwarren** [comment]
It's an S3 method for enmtools.maxent models, which means you should be able to just call predict(your.model).  You don't need to call predict.enmtools.maxent explicitly.  Give that a shot and tell me if it doesn't work.  Cheers!
