### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by MichelleDBG** [danlwarren/ENMTools#145]
In both an install_github and install_local I get the following error:

Error in read.dcf(path) : Found continuation line starting '	person("Olivier", " ...' at begin of record.
17.
read.dcf(path)
16.
is.data.frame(x)
15.
colnames(read.dcf(path))
14.
read_dcf(tmp)
13.
remote_package_name.github_remote(x)
12.
remote_package_name(x)
11.
FUN(X[[i]], ...)
10.
vapply(remote, function(x) remote_package_name(x), character(1), USE.NAMES = FALSE)
9.
remote_deps(pkg, ...)
8.
combine_deps(package_deps(deps, repos = repos, type = type), remote_deps(pkg, ...))
7.
dev_package_deps(pkgdir, repos = repos, dependencies = dependencies, type = type, ...)
6.
install_deps(pkgdir, dependencies = dependencies, quiet = quiet, build = build, build_opts = build_opts, upgrade = upgrade, repos = repos, type = type, ...)
5.
install(source, dependencies = dependencies, upgrade = upgrade, force = force, quiet = quiet, build = build, build_opts = build_opts, repos = repos, type = type, ...)
4.
FUN(X[[i]], ...)
3.
vapply(remotes, install_remote, ..., FUN.VALUE = character(1))
2.
install_remotes(remotes, dependencies = dependencies, upgrade = upgrade, force = force, quiet = quiet, build = build, build_opts = build_opts, repos = repos, type = type, ...)
1.
install_local("C:/Users/deprengm/Downloads/ENMTools-master.zip")

**Comment by danlwarren** [comment]
Yeah, this is an issue with ecospat's DESCRIPTION file.  The solution is quite easy, luckily; just install ecospat manually first, and everything's fine.
