### ISSUE TITLE
background for Environmental Space 

### ISSUE THREAD

**Issue by ppagliosa** [danlwarren/ENMTools#152]
Dear Dan Warren,
thank you for the enmtools!

I want to change the background values in the Environmental Space analysis.
What I understood reading your codes is that for Environmental Space analysis 
the number of points for the background in enmtools."MODELs" are called by the function "env.evaluate" (nbackground = 10000); and the number of background points in hypothesis tests (identity.test, background.test, and rangebrake."TESTs", etc) are called by the function "env.overlap" (chunk.size = 1e+05). 

I tried to include the argument "nbackground" while running enmtools."MODELs" and it didn't work. How may I choose the values of background for the Environmental Space analysis in enmtools."MODELs" and hypothesis tests?
best regards,
Paulo

**Comment by danlwarren** [comment]
The number of points for the hypothesis tests are specified by the argument "nback" for the hypothesis tests.

**Comment by danlwarren** [comment]
The argument for the enmtools model functions (enmtools.glm, enmtools.maxent, etc.) is "nback", not "nbackground".  Is that what you were asking?

**Comment by ppagliosa** [comment]
Dear Dan Warren,
thank you for your answer. 
The "nback" set the background values for the Geographical Analysis (D, I and rank.cor), not for the Environmental Space analysis (env.D, env.I and env.cor). 
When running enmtools models functions (e.g., enmtools.bc) or test functions (e.g., identity.test) the Environmental space analysis uses the default value of 10000. This value came from the default values of the inner functions "env.evalueate" (in enmtools models functions; e.g, lines 70, 79, 91, 140 and 149 from "enmtools.bc.R") and "env.overlap" (in test functions; e.g., lines 109 and 170 from "background.test.R").

There are many papers discussing the impact of the background values in the ENMs and may be useful to change this value in Environmental space analysis too. May I suggest you include an argument like "env.nback" in enmtools model functions and test functions to allow the user to choose change those values to run Environmental Space analysis.
best wishes,
Paulo

**Comment by danlwarren** [comment]
Ah!  I get what you're saying now.  That should be relatively easy to implement.

**Comment by danlwarren** [comment]
Aaaaand it's done!  Possibly.  I just pushed the changes to the "develop" branch, and they're checking now.  If you want to reinstall from develop and try it, you can do that at any time.  Cheers!
