### ISSUE TITLE
potential raster.overlap bug

### ISSUE THREAD

**Issue by jmhatch** [danlwarren/ENMTools#160]
Looking at the code for `raster.overlap` and I may have found a bug. Shouldn't this:

`I <- 1 - cellStats((sqrt(x) - sqrt(y))^2, stat=sum)/2`

be this:

`I <- 1 - sqrt(cellStats((sqrt(x) - sqrt(y))^2, stat=sum))/2`

based on Warren et al. (2008). Not sure if it makes a huge difference.

**Comment by jmhatch** [comment]
I've also been wondering whether I (the similarity statistic) should be calculated as:

`I <- 1 - sqrt(cellStats((sqrt(x) - sqrt(y))^2, stat=sum) / 2)`

Because isn't the Hellinger distance bounded between `[0, sqrt(2)]`?

**Comment by danlwarren** [comment]
> Looking at the code for `raster.overlap` and I may have found a bug. Shouldn't this:
> 
> `I <- 1 - cellStats((sqrt(x) - sqrt(y))^2, stat=sum)/2`
> 
> be this:
> 
> `I <- 1 - sqrt(cellStats((sqrt(x) - sqrt(y))^2, stat=sum))/2`
> 
> based on Warren et al. (2008). Not sure if it makes a huge difference.

We actually got the equation wrong in the 2008 paper.  We published a corrigendum on it when it came up when Rödder and Engler discovered the error.  There's a blog post about it here:

http://enmtools.blogspot.com/2010/09/error-in-i-metric-but-dont-panic.html

**Comment by jmhatch** [comment]
That clears things up, thanks!
