### ISSUE TITLE
Error when running identity.test in a loop

### ISSUE THREAD

**Issue by momeni133** [danlwarren/ENMTools#161]
Hello everyone, 
I need to run the "identity.test" function for multiple species (pairwise). As the number of iterations is high, if I run this for each pair separately, it takes a long time to be completed because it seems that the ENMtools is based on a single (CPU)core processing. Therefore, I decided to run it in a "foreach" loop to calculated the identity test for different species at the same time.
In this regard, I made a list and added all the "enmtools.species" into that list. then I used the below code to run the "identity.test":
` 
detectCores()
cl <- parallel::makeCluster(7)
doParallel::registerDoParallel(cl)

foreach(i = 1:4) %dopar%  {
  for(j in 1:4) {
    identity_test[[paste(j, i, sep="_")]] <- ENMTools::identity.test(species_list1[[i]],species_list2[[j]],env_stck, type="mx", nreps = 100, nback = 5000, bg.source = "points")
    }
}`
However, I received the following error message when I used this code:

> Error in { : 
>   task 1 failed - "no applicable method for 'predict' applied to an object of class "c('MaxEnt', 'DistModel')""

I spent a lot of time on this problem, but I didn't find any solutions for that. What could be the potential source of that error?
PS. outside of the loop, the "identity.test" works perfectly when I have just one pair of species.

**Comment by danlwarren** [comment]
Does it work with other model types?  My first guess would be that foreach isn't working well with dismo's system calls to Java/Maxent.
