### ISSUE TITLE
ERROR IN INSTALLING ENMTools package in R

### ISSUE THREAD

**Issue by JEFFGAFNA16** [danlwarren/ENMTools#162]
install.packages("rJava") # reinstall if you switch from x64 to x32 R version
library(rJava)
install.packages("devtools", dependencies = T) 
library(devtools) 
# install the x64 and x32 version of JDK first, rather than JRE
Sys.setenv(JAVA_HOME="")
Sys.setenv(JAVA_HOME="C:\\Program Files\\Java\\jdk1.8.0_171\\")
# Sys.setenv(JAVA_HOME="C:\\Program Files (x86)\\Java\\jdk1.8.0_171\\") # for 32-bit R version, if the 64-bit is not working

Install_github("danlwarren/ENMTools") # If the error "Error : object 'descendants' is not exported by 'namespace:phyloclim'", use develop brach, ie:
install_github("danlwarren/ENMTools",ref="develop") 
1# , missing ecospat package
install.packages(c('ade4', 'adehabitatHR', 'adehabitatMA', 
                   'biomod2', 'ecodist', 'maptools', 'rms', 'MigClim', 'gtools', 
                   'PresenceAbsence', 'classInt')) 
install.packages("C:/Users/Dikko-Admin/Documents/R/win-library/3.5/ecospat_2.2.0.tar.gz", 
                 Repos = NULL, type = "source") # Install the downloaded ecospat package, change the path to your own

install_github("danlwarren/ENMTools",ref="develop") 

I came across your script on how to install ENMTool package in R. However, I have been facing errors.  When I run line "install_github("danlwarren/ENMTools",ref="develop")"  of the script, I get the error attached on screenshot 1   

Error: Failed to install 'ENMTools' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘ps’​.  

I attempt to solve this error by using the function  .libPaths() to locate the folder 'ps' in my computer and delete it.  After doing this,  I now run the script from the top but I get an error on line "library(devtools)" when checking for devtools using "library(devtools)". 

### Loading required package: usethis
Error: package or namespace load failed for ‘devtools’:
 .onLoad failed in loadNamespace() for 'processx', details:
  call: loadNamespace(name)
  error: there is no package called ‘ps’
In addition: Warning messages:
1: package ‘devtools’ was built under R version 3.5.3 
2: package ‘usethis’ was built under R version 3.5.3 

This scenario keeps on repeating itself not only with "ps" package but also other packages like  "digest", "fansy" etc. How can I go about this 
Am using windows 10 computer, version 3.5.1,  and 64-bit). I know you are very busy and would really appreciate your help.

Kind Regards,

Dikko

**Comment by danlwarren** [comment]
I honestly have no idea.  This sounds like some sort of issue with your R installation rather than an issue with ENMTools itself.  My suggestion would be to install the newest version of R and then reinstall all packages, ideally uninstalling your existing R installation first.
