### ISSUE TITLE
environmental variables - identity test

### ISSUE THREAD

**Issue by almeidathamara** [danlwarren/ENMTools#163]
Hello @danlwarren,

I want to test the niche differentiation hypothesis for the same species, comparing past (2000s) and present (2020) occurrence data and environmental data at these different times in the identity test. However, the function only accepts a group of variables. Is it possible that a modification in the code is incorporated for this type of analysis?

**Comment by danlwarren** [comment]
Replying via email.  The quick answer is that you can do this by modifying your rasters and points so that the different time periods essentially look like two different geographic areas.  It's a decent chunk of work, though.
