### ISSUE TITLE
Functions for calculating AICc and BIC for Maxent models

### ISSUE THREAD

**Issue by plantarum** [danlwarren/ENMTools#164]
Hello,

Warren and Seifert (2011) and Warren et al. (2014) cite ENMTools as a source of functions for calculating AIC/BIC values for Maxent models. This aprroach was used in a 2018 paper [1] that cited these sources and your package.

I have installed your package, and used it to create a Maxent model with my data. The output doesn't appear to include AIC values, and I don't see anything in the manual that indicates how I should do this. Are these functions still available? My apologies if I've overlooked something.

Best,

Tyler

[1] Lee‐Yaw, J.A., Fracassetti, M. and Willi, Y. (2018), Environmental marginality and geographic range limits: a case study with Arabidopsis lyrata ssp. lyrata. Ecography, 41: 622-634. doi:10.1111/ecog.02869

**Comment by danlwarren** [comment]
The AIC stuff was in the standalone version of ENMTools, but is not in the R package because these methods are already implemented in the ENMEval R package.
