### ISSUE TITLE
Hook modeling functions into vip to get variable importance

### ISSUE THREAD

**Issue by danlwarren** [danlwarren/ENMTools#178]
https://cran.r-project.org/web/packages/vip/index.html

Might take a bit of work to do this for Maxent models, but otherwise should be pretty tractable.

**Comment by danlwarren** [comment]
Here's some demo code to use various methods to get variable importance scores using different methods from the vip package.  Several of its methods are incorporated via "suggests", and as such those packages need to be install separately.

install.packages("vip")
install.packages("pdp") # needed for "firm" method
install.packages("fastshap") # needed for shapley method
library(vip)
library(ENMTools)
data("iberolacerta.clade")
data("euro.worldclim")

monticola.glm <- enmtools.glm(iberolacerta.clade$species$monticola,
                              euro.worldclim,
                              test.prop = 0.3)

vip(monticola.glm$model, num_features = 19)

# Just figuring out how to use the different functions here
# "model" method can be called using no external packages or need
# to input training df, but the others require more work
test.model <- vi_model(monticola.glm$model)

test.permute <- vi_permute(monticola.glm$model, 
                           feature_names = labels(terms(monticola.glm$model)),
                           train = monticola.glm$analysis.df[,-c(1,2)],
                           target = "presence", 
                           metric = "auc",
                           pred_wrapper = predict,
                           reference_class = "1",
                           nsim = 100)

test.shap <- vi_shap(monticola.glm$model, 
                     feature_names = labels(terms(monticola.glm$model)),
                     train = monticola.glm$analysis.df[,-c(1,2)],
                     pred_wrapper = predict,
                     nsim = 100)

test.firm<- vi_firm(monticola.glm$model,
                    feature_names = labels(terms(monticola.glm$model)),
                    train = monticola.glm$analysis.df[,-c(1,2)],
                    target = "presence", 
                    metric = "auc",
                    pred_wrapper = predict,
                    reference_class = "1",
                    nsim = 100)

**Comment by danlwarren** [comment]
Making notes to myself here:

The "model" method doesn't work for GAM.  It tries (presumably using the "lm" class implementation) but returns 

```
Error in abs(coefs[, pos]) : 
  non-numeric argument to mathematical function
```

None of the vi functions work for bioclim or domain, but that's not surprising.  Not sure what sense VI scores would make for these models anyway.

Maxent models fail with the same text as BC and DM: `Error: $ operator not defined for this S4 class`

ppmlasso models fail with: `Error in terms.default(monticola.ppm$model) : 
  no terms component nor attribute`

**Comment by danlwarren** [comment]
Basically GLM and RF work off the shelf with the code above but everything else is going to require some fiddling.

**Comment by danlwarren** [comment]
Ultimately it'd be very nice to get this working for all of the different model types and then have ENMTools spit out ridgeline plots when nsim > 100.  That'd mean importing ggridges but I think those might actually be cool for other plots anyway.

**Comment by danlwarren** [comment]
Starting a new "vip" branch to work on this.

**Comment by danlwarren** [comment]
Well I'll be darned, it appears to be working!

**Comment by rdinnager** [comment]
👍 Awesome!

**Comment by danlwarren** [comment]
It's pretty neat!  I'm actually reworking the plots now to get similar-looking output without importing ggridges or forcats.  Getting close.
