### ISSUE TITLE
Add spThin and other methods for thinning data

### ISSUE THREAD

**Issue by danlwarren** [danlwarren/ENMTools#191]
We've discussed this in the past, but it was again suggested by a reviewer of the application note.   Seems like an obvious thing to do.  We'll need to explore which methods are available, though.  I'd suggest we default to the relatively fast point -> raster -> point method, and then make the more computationally intensive methods optional.

**Comment by nahuron** [comment]
@danlwarren are you beholden to a particular package to hook in for this (or were you thinking of creating something from scratch)? I did a test this AM on some big datasets I am using (~10^5 records to thin) and `spThin::thin` crapped out on me with memory problems. I have used `humboldt::humboldt.occ.rarefy`, which differs in method a bit but did not break. I will continue to poke around on other methods either way!

**Comment by danlwarren** [comment]
Yeah actually given how many dependencies we have it might be better to just roll our own.  In my experiences spThin is mostly useful for very small data sets, and just chokes when you give it anything large.  It looks like all that humboldt is doing is getting a distance matrix and cutting the points with the lowest nearest neighbor distances until the lowest NN distance is above the threshold distance the user sets.  That should be pretty easy to recreate in ENMTools.  

There's another method that can be much faster for very large data sets where you convert your points to a raster at the desired resolution and then convert the raster back to points.  This moves the occurrences to the center of their respective grid cells, though, so it mostly makes sense if you just want to trim the data to one point per grid cell using the environment layers.

**Comment by nahuron** [comment]
Ah I see what you meant at the bottom of the request!

Yes, humboldt seems to be doing exactly that.

 I am happy to dig into trying to add a function that can use one or both of the methods
