### ISSUE TITLE
URGENT: Update for spatstat 2.0

### ISSUE THREAD

**Issue by danlwarren** [danlwarren/ENMTools#197]
Okay spatstat is being split out into sub-packages now, and ENMTools is going to be kicked from CRAN if we don't update to match the new changes by the 28th.

https://github.com/rubak/spatstat.revdep/blob/main/README.md

**Comment by danlwarren** [comment]
Unless I am mistaken, the only things being called from spatstat directly are in the sim.points function.  If it comes down to it, we might just yank this function out until we can get things fixed.

**Comment by rdinnager** [comment]
Oh yeah I heard about that. Hmm.. sounds like it is hopefully not too big a job. I wonder if we could use one of those dependency graph packages to double check where else, if anywhere, spatstat is being used? e.g. https://github.com/uptake/pkgnet

**Comment by danlwarren** [comment]
Ah, good idea.  I used pkgnet and it definitely looks like we've got some indirect dependencies on spatstat too.

As a side note, we were supposed to get some sort of email about these spatstat changes a month or two ago so that we could prepare.  I didn't get one, did you?

**Comment by rdinnager** [comment]
No, I didn't get an email about this. I just heard about it yesterday via twitter (`sf` package maintainer tweeted about it). I guess for indirect dependencies we have to rely on the intermediate package authors fixing it on their end?

**Comment by danlwarren** [comment]
Okay I've run through the update routine for spatstat 2.0.  Github Actions builds are currently working for Mac and Windows, but not for Ubuntu.  The Ubuntu build says ppmlasso isn't available, which I reckon is because of its own dependency on spatstat.

**Comment by danlwarren** [comment]
I've now gotten my first email from someone who can't install the CRAN version of ENMTools because of this.  We may have to take the nuclear option here and temporarily remove the ppmlasso stuff until we can get this sorted.

**Comment by rdinnager** [comment]
I'm okay with that if necessary. I try and have a look today to see if there is any other way around it.

**Comment by rdinnager** [comment]
Jut had a quick look. I don't think not being able to install a package in Suggests should be a problem for installing ENMTools, so we could just set the `_R_CHECK_FORCE_SUGGESTS_` environmental variable to `false` in the github actions yaml, which would then just not check whether suggested packages can be installed, as away to get the CI to pass for now. But I don't know if all Suggested packages being able to be installed is required to pass CRAN checks? Regardless, the functions that rely on `ppmlasso` will not work anymore. I wonder why this only fails on Linux though?

**Comment by danlwarren** [comment]
Yeah I'm much more concerned with the CRAN issue than with the github actions.  However I've heard from Will Banks that installing the version on **develop** works with the newer versions of **spatstat**, so my attempt to update everything last Friday seems like it might have worked.  I'm going to run some more checks and then try uploading the current dev version to CRAN.

**Comment by rdinnager** [comment]
Yes, this makes sense. I've just quickly reviewed the CRAN policy and it seems as if packages in Suggests failing to install should not be an issue, so hopefully all should be well when you upload it. If you want I can just quickly push a change to fix the Github Actions for now?

**Comment by danlwarren** [comment]
Will do!

**Comment by danlwarren** [comment]
Okay the linux build on github still seems to be having issues with rgdal but those go way back so I'm not sure we should have expected them to be fixed.

**Comment by danlwarren** [comment]
All right CRAN kicked it back with a note that ppmlasso isn't available on linux.  Everything else seems fine.  I think we're just going to have to remove ppmlasso from the CRAN version until they get it back online.

**Comment by rdinnager** [comment]
Okay, I guess that is the only option left. I will try emailing Ian Renner to see if he plans on fixing `ppmlasso`. He may not have gotten any email warning from spatstat the same way we didn't. I see that it has been archived by CRAN now. We may have to drop it permanently. There are now better ways of fitting point process models in R, though generally they are more involved and slower (using stan or INLA), but I have been considering writing a user-friendly wrapper around INLA for fitting them, and maybe ENMTools would be a sensible place to put something like that? I don't know when I would have time for something like that though. Maybe when we are ready to start the grand `tidymodels` refactoring?

**Comment by danlwarren** [comment]
Implementing INLA would be awesome, but yeah I think it should go in the context of the tidymodels change if we do it.  There's just no point to implementing a new method that's that involved when we know we're going to overhaul everything before the next release anyway.
