### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by burbrink** [danlwarren/ENMTools#198]
Hi Dan,

I realize you guys are working out a solution to this spatstat issue. Do you have any workaround to get ENMTools properly installed into Mac in the meantime?

The error of course is: Error: object ‘rpoispp’ is not exported by 'namespace:spatstat' Execution halted

Thanks.

Frank

**Comment by danlwarren** [comment]
Right now all you can do is install the develop version from github.  Luckily it's not too hard, just:

install.packages("devtools")
devtools::install_github("danlwarren/ENMTools", ref = "develop")

So far that seems to be working for people, but let me know if it doesn't work for you!

**Comment by burbrink** [comment]
Hey Dan,

Thanks for the response. I have only every loaded this from github and still get that error.

Frank

**Comment by burbrink** [comment]
Let me give it another shot with the develop branch. My R is running a stupidly long job now and then I'll get to it (later).

Thanks again Dan.

**Comment by burbrink** [comment]
Ok, switched to my terminal and this does it with the develop branch. Thank you! 

To note, on the code page it does not have ref = "develop" part of the argument. 

Thanks again!

Frank

**Comment by danlwarren** [comment]
Ah yeah, that's new just for this issue - I'm actually moving the changes over to the main branch right now so it shouldn't be required for long.  Cheers!
