### ISSUE TITLE
Setting use of MaxEnt model in the identity.test function

### ISSUE THREAD

**Issue by FernandoMoroC** [danlwarren/ENMTools#210]
How can I set  features and regularization coefficient in MaxEnt model when I use type="mx" in identity.test?

**Comment by danlwarren** [comment]
You should be able to just pass in a "params" vector just as if you were calling it from enmtools.maxent().

**Comment by tinsman** [comment]
Hi @danlwarren, I used ENMeval to pick some appropriate maxent parameters for the two species I'd like to compare using the identity test. I settled on different parameters for both species. (e.g. L 4 for Species A, which has fewer points than Species B, for which the model built using LQH 1 performs best).
What parameters would you recommend for the pseudo-replicates in that case? Average the regularization multipliers? Select the most (or least) complex features? Blob them both together, re-run ENMeval, and see what comes out there? I wonder what makes the most biological sense.
