### ISSUE TITLE
background.buffer needs to be exported in NAMESPACE

### ISSUE THREAD

**Issue by plantarum** [danlwarren/ENMTools#218]
You've provided a new general `background.buffer` function, intended to replace `background.raster.buffer`, `background.points.buffer` etc:

https://github.com/danlwarren/ENMTools/blob/a23f4bf4b9acf7f04548c2e97a2cee7c0372d975/NEWS.md?plain=1#L34

I think this is intended to be used by users? If so, it needs to be added as an export in the NAMESPACE file so we can access it!

Thanks,

tyler

**Comment by danlwarren** [comment]
Aaaag I had done this on develop but never did a PR to main for it.  Thanks!
