### ISSUE TITLE
documentation for geog.range.overlap

### ISSUE THREAD

**Issue by plantarum** [danlwarren/ENMTools#221]
Currently this is explained as "calculates overlap between them as in Fitzpatrick and Turelli 2006"

After looking up that reference, I see that what happens is:

"The  degree  of  overlap  between  two  species  was  calculated as the ratio of the area of overlap to the area of the smaller  of  the  two  ranges... This  way,  if  one  range  is  contained  within  another,overlap is 100%."

Could you add that quote to the documentation? It would save the user having to look up the paper, and I'll definitely forget this detail by the next time I use this function.

Thanks,

Tyler

**Comment by danlwarren** [comment]
This is added on test now, it'll propagate elswhere as I make more changes.  Thanks for the suggestion!
