### ISSUE TITLE
documentation for raster.breadth

### ISSUE THREAD

**Issue by plantarum** [danlwarren/ENMTools#225]
The documentation for `raster.breadth` includes the description:

```
Description:

     This function measures the spatial heterogeneity of the
     distribution of suitability scores from an ENM.  It returns
     Levins' two metrics of niche breadth.

...

Value:

     results A vector containing the two metrics B1 and B2 for niche
     breadth.
```

I think this refers to Levins (1968)? Could you add that reference to the help page, and maybe include the formulas as well?

$\text{log } B = - \sum p_i \text{ log } p_i$

$1/B = \sum p_i^2$

Levins, R. 1968. Evolution in changing environments: some theoretical explorations. Princeton University Press.

**Comment by danlwarren** [comment]
Done, thanks for the suggestions!
