### ISSUE TITLE
`background.buffer()` gives uninformative error when it produces no points

### ISSUE THREAD

**Issue by rdinnager** [danlwarren/ENMTools#226]
If `background.buffer()` produces no points (for example, if `mask` and `points` don't overlap), then it gives this error:
```
Error in xy[sample(1:nrow(xy), n, replace = TRUE), ] : 
  subscript out of bounds
``` 

This is because it is trying to sample an empty matrix. We should check if `xy` has zero rows and give an informative error message like "Unable to sample any points, this could be because your mask and points do not overlap". Or possibly that could be a warning, and we return the empty points matrix?

**Comment by danlwarren** [comment]
Fixed!
