### ISSUE TITLE
Issue with clamp.env while running identity.test()

### ISSUE THREAD

**Issue by ascanioalfredoa** [danlwarren/ENMTools#246]
Hello All!

We were trying to run some identity tests and got an error that we could not easily identify. Later, it turned out to be within the clamp.env() call at the beginning of the function. The error had to do with some subsetting error, but I apologize that I don't have the exact error message at the time. My solution was to change the clamp.env() function from

```
for (i in names(clamped.env)) {
    thismin <- min(df[, i])
    thismax <- max(df[, i])
    clamped.env[[i]][clamped.env[[i]] > thismax] <- thismax
    clamped.env[[i]][clamped.env[[i]] < thismin] <- thismin
 }
```

to

```
for (i in names(clamped.env)) {
    thismin <- min(df[, i])
    thismax <- max(df[, i])
    clamped.env[[i]] <- clamp(clamped.env[[i]], lower = thismin, upper = thismax, values = TRUE)
  }
```
The error originally happened in any of these two lines, trying to reasign the max and min values due to clamping

```
    clamped.env[[i]][clamped.env[[i]] > thismax] <- thismax
    clamped.env[[i]][clamped.env[[i]] < thismin] <- thismin
```

Using the [terra::clamp()](https://rspatial.github.io/terra/reference/clamp.html) function seemed to solve it, but it was somewhat slow.  I'm unsure as to why this error happened in the first place, because terra is supposed to have natural replacement (https://rspatial.github.io/terra/reference/replace_values.html). I also tried with [terra:subst()](https://rspatial.github.io/terra/reference/subst.html), but it was extremely slow.

**Comment by ascanioalfredoa** [comment]
Sorry, I think I found the real issue. It seems to do with using the `names(clamped.env)` as `i` in the loop. I was still having the issue but this fixed it:

```
for (i in 1:length(names(clamped.env))) {
    thismin <- min(df[, i])
    thismax <- max(df[, i])
    clamped.env[[i]] <- clamp(clamped.env[[i]], lower = thismin, upper = thismax, values = TRUE)
  }
```

**Comment by danlwarren** [comment]
I can't replicate the issue here.  What happens on your end if you try it with the demo data?
