### ISSUE TITLE
An unusual value for Shoener's D calculated using raster.overlap

### ISSUE THREAD

**Issue by momeni133** [danlwarren/ENMTools#249]
Hi Dan,
I am trying to calculate shoener's D for a pair of rasters but the function gives me a negative value for this. I have attached sample raster files below. On my computer the output for: 
raster.overlap(raster1, raster2) is: 
$D
[1] -0.7913785

$I
[1] 0.8513937

$rank.cor
[1] 0.9981802

Do you know what could be a possible reason for this?
[rasters.zip](https://github.com/danlwarren/ENMTools/files/13923311/rasters.zip)

**Comment by danlwarren** [comment]
Yep, something got broken here when we moved to terra so that it wasn't dealing correctly with negative values.  I'll fix it shortly.  Sorry!

**Comment by danlwarren** [comment]
Okay if you install from the develop branch on github it should be fixed now.  I'll push to main sometime in the next few days - doing a whole bunch of maintenance at once right now.
