### ISSUE TITLE
Error in Warren's I Calculation

### ISSUE THREAD

**Issue by abbycperkins** [danlwarren/ENMTools#264]
Function raster.overlap calculates Warren's I as follows: 
` I <- 1 - as.numeric(terra::global((sqrt(x) - sqrt(y))^2,  "sum", na.rm = TRUE)/2)`

Based on the equations presented in the Warren 2008 paper, this calculation should have an additional square root after the sum to achieve the Hellinger distance calcluation. Is there a reason I is being calculated differently in this function?

**Comment by danlwarren** [comment]
The original article has an error in the formula.  There's a correction here:

https://onlinelibrary.wiley.com/doi/10.1111/j.1558-5646.2010.01204.x

**Comment by abbycperkins** [comment]
Thank you!

**Comment by danlwarren** [comment]
No worries!
