### ISSUE TITLE
Niche Overlap

### ISSUE THREAD

**Issue by momeni133** [danlwarren/ENMTools#64]
Dear ENMtools users/developers

As a part of my research, I want to calculate “niche overlap” for two species (one carnivore and one herbivore species). I have used MaxEnt to produce ENM for each one in the raw format (MaxEnt 3.4.1). I found that there are some functions in ENMtool which can be used for this purpose, but my problem is that these suitability layers have resulted from different background points (10000 points) and also the number of presence points which are used in MaxEnt is not same for these species. Could you please tell me your point of view in this way?

 

Best regards

**Comment by danlwarren** [comment]
It shouldn't be an issue.  These metrics only measure the similarity between predictions made by models, and aren't directly affected by the number of background points or the number of presence points.

**Comment by momeni133** [comment]
Thank you very much for your quick response.
Do you know any papers in this regards? This issue is my concern because of following paragraph in Otis et al. 2017:
"Because sample size and background environments differed
between each canid group, niche overlap values could not be compared
directly (Peterson, 2011). Rather, we used a null model approach
which tests that niches of two populations are more similar
than expected based on chance alone, using a background similarity
test (Warren, Glor & Turelli, 2008)."


Otis, J.-A., et al. (2017). "Ecological niche differentiation across a wolf-coyote hybrid zone in eastern North America." Diversity and Distributions 23(5): 529-539.

**Comment by danlwarren** [comment]
That means that you can't say much about what that measurement of overlap means without testing it against a null hypothesis, as you do in ENMTools.  It doesn't mean that the measurement itself is invalid.

**Comment by momeni133** [comment]
Is it possible to test results of ENMs against a null hypothesis in
ENMtools? I mean doing such a test for ENMs which are not developed inside
the ENMTools.
Whole of my study is based on MaxEnt 3.4.1.

Best regards
Iman


Iman Momeni
Ph.D. candidate in Environmental Sciences -  Land Use Planning
Faculty of Natural Resources
Isfahan University of Technology (IUT)

**Comment by danlwarren** [comment]
Not the R version, no.  But the R version allows you to use whatever version of Maxent you want from within ENMTools via dismo, so I'm not sure why you'd need to.  If you just really need to interact with the Maxent GUI for something (e.g., if you need to do something that you can't pass via arguments through dismo), you may have to do something more complex by hand.

**Comment by momeni133** [comment]
Thank you,
I will redo modeling steps using ENMtools in R
