### ISSUE TITLE
How to run ENMTools using predefined regulirization multiplier, feature type and background points

### ISSUE THREAD

**Issue by momeni133** [danlwarren/ENMTools#66]
Dear ENMTools users
I need to use this package to produce habitat suitability layers for some species. I have found the optimum regularization multiplier and also feature type before, but I can't find the relevant arguments for these settings in "enmtools.maxent". also I have the same problem to use predefined background points instead of random points. Any comments to solve the problem is highly appreciated.

**Comment by danlwarren** [comment]
What enmtools.maxent does is it passes any arguments it doesn't recognize to the dismo maxent() function.  So as long as there are arguments for those settings that maxent() accepts, you can just pass those to enmtools.maxent.
