### ISSUE TITLE
plot.enmtools.species does not work if the enmtools.species object has no `range` 

### ISSUE THREAD

**Issue by rdinnager** [danlwarren/ENMTools#70]
If the `enmtools.species$range` is empty, `plot.enmtools.species` does not work, because plotting the presence and background points is done with `points()`, which does not work if there is not already a plot on the graphics device (which only happens if the 'range' slot is not missing, currently.

**Comment by danlwarren** [comment]
Yeah, I'm aware of this one but I don't really know what a good alternative is - throwing up a plot with just some points in a blank field?  Seems a bit uninformative.

I actually did a branch a few months ago that had a built-in world map that was used for default plots, but both the size of the map and the plotting were causing issues so I abandoned it.  

If you have a good idea for other options, I'm all for it!

**Comment by rdinnager** [comment]
That makes sense. On the other hand, I think a blank plot with only the points is better than nothing, since then at least the user can a) make sure the points have sensible / expected coordinates, and how they are arranged with respect to each other (e.g. see how evenly or unevenly they are distributed, etc., b) see how many presence points there are and where they fall with respect to the background points (for user specified bg points in particular). It's just useful for a quick inspection basically, rather than trying to eyeball the numbers. I'll have a go at adding something for this. 

As for the map thing, one thought I've had is to incorporate the leaflet package into ENMTools (https://rstudio.github.io/leaflet/). This allows you to create an interactive map using the leaflet javascript library really quickly and easily. It's great because then you can just scroll around and zoom in and out of your points, and the maps are all publicly stored online, so it doesn't bloat your package. Anyway, maybe I'll make a branch to try this out, and then you can see what you think? Maybe make it a separate function, so users can ignore it if they don't have an internet connection, etc.

**Comment by danlwarren** [comment]
That would be awesome!  By the way, I don't think I mentioned this yet: in order to pass CRAN checks I had to stop roxygen2 from managing imports.  Any functions you need to import from a package now need to be manually specified in the importFrom() entries in the namespace file.

**Comment by danlwarren** [comment]
Oh yeah - with respect to grabbing plots from online: I'm sure you've already thought of this but there's definitely going to need to be a switch in there to fail gracefully if there's no internet connection.
