### ISSUE TITLE
Get better demo data and code

### ISSUE THREAD

**Issue by danlwarren** [danlwarren/ENMTools#8]

**Comment by rdinnager** [comment]
I could probably contribute some Banksia and Hakea data from SW Australia if that would help?

**Comment by danlwarren** [comment]
I was thinking something with two species on a relatively small island, maybe two environmental layers.  Something a lot like the ahli/allogus data that's already in there, but with more occurrence points.  Size of test data gets to be a real issue when you're submitting packages to CRAN.

**Comment by nahuron** [comment]
What sort of island size are we talking? Depending on when I can get my Brachymeles manuscript shipped off, there might be a species pair that would work well for one of the islands in the Philippines.

**Comment by danlwarren** [comment]
It's more about file size than geographic size, so of course resolution can be a huge component of that.

Actually, the ideal situation would be:

A small clade (maybe ~5 species)
Decent amount of occurrence data
Around four climate layers
Phylogeny

Ideally all would compress into about 4 MB.

**Comment by rdinnager** [comment]
Perhaps we should also include some simulated data? Then we can make it whatever size we want, and make it demonstrate whatever functionality we want. Plus it would probably make sense to have some simulated data for making testthat tests..

**Comment by danlwarren** [comment]
Yeah, actually that might be the most size-efficient way to do it.  We could set up some code to specify some simple niches and a tree for a small clade of organisms, and then for "environments" have some spatially-autocorrelated random fields in a raster stack.  That way we could just generate the demo data on the fly as we write example code, storing nothing.  

That is, of course, as long as the demo data can be simulated quickly.  CRAN also has a requirement about runtime for sample code.

**Comment by danlwarren** [comment]
Okay so we may not want to do this bit on the fly, but we can simulate spatially autocorrelated rasters and zip those up as part of the sample data.  Simulating the species with base R code and stuff we're already importing should be significantly easier.

![image](https://user-images.githubusercontent.com/3770891/33014480-c0f4709a-cde7-11e7-8a1b-d42a2386e52b.png)

Based on code from here: http://santiago.begueria.es/2010/10/generating-spatially-correlated-random-fields-with-r/

Along with some janky post-processing to generate correlations between predictors.

**Comment by danlwarren** [comment]
I've actually attached some demo data to the Cranify branch.  It's a clade of Iberian lizards and a low-res European set of Worldclim layers.  I'm rewriting demo code now to work with the included data set.
