### ISSUE TITLE
Argument to define accessible area

### ISSUE THREAD

**Issue by danlwarren** [danlwarren/ENMTools#85]
Need to have an argument for the modeling functions that allows you to override default ordering of background points/range/env rasters.

**Comment by rdinnager** [comment]
I would find this useful.

**Comment by danlwarren** [comment]
An additional really nice thing would be to do some sort of NMDS comparison of the distribution of environments in the training data vs. the distribution of environments in the projected area.  This would be useful for the predict function, but we could also use it here when the background region and the extent of the env layers is different.

This could be a 2d NMDS env space plot, or we could make a map somehow.  Or both, ideally.

**Comment by danlwarren** [comment]
I've actually implemented this now as threespace.plot, but we can expand on it as we go on.
